// Authentication
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REDIRECTED = 'REDIRECTED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//cart
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_NEW_PRODUCT_TO_CART_SUCCESS"
export const ADD_PRODUCT_TO_CART_ERROR = "ADD_NEW_PRODUCT_TO_CART_ERROR"
export const REMOVE_PRODUCT_FROM_CART_SUCCESS = "REMOVE_PRODUCT_FROM_CART_SUCCESS"
export const REMOVE_PRODUCT_FROM_CART_ERROR = "REMOVE_PRODUCT_FROM_CART_ERROR"
export const UPDATE_QUANTITY_PRODUCT_IN_CART_SUCCESS = "UPDATE_QUANTITY_PRODUCT_IN_CART"
export const UPDATE_SELECT_PRODUCT_IN_CART_SUCCESS = "UPDATE_SELECT_PRODUCT_IN_CART"

//order
export const APPLY_COUPON_BEGIN = "APPLY_COUPON_BEGIN"
export const APPLY_COUPON_SUCCESS = "APPLY_SUCCESS"
export const APPLY_COUPON_ERROR = "APPLY_COUPON_ERROR"
export const CHECKOUT_PRODUCT_BEGIN  = "CHECKOUT_PRODUCT_BEGIN"
export const CHECKOUT_PRODUCT_SUCCESS = "CHECKOUT_PRODUCT_SUCCESS"
export const CREATE_ORDER_BEGIN = "ORDER_BEGIN"
export const CREATE_ORDER_SUCCESS = "ORDER_SUCCESS"
export const CREATE_ORDER_ERROR =  "ORDER_ERROR"
export const REMOVE_ORDER_SUCCESS = ""
export const REMOVE_ORDER_ERROR = ""
export const REMOVE_ORDER_BEGIN = ""
//user-profile

export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const ADD_NEW_ADDRESS_SUCCESS = "ADD_NEW_ADDRESS_SUCCESS"
export const UPDATE_PROFILE_PICTURE_SUCCESS = "UPDATE_PROFILE_PICTURE"
export const UPDATE_PROFILE_PICTURE_ERROR = "UPDATE_PROFILE_PICTURE_ERROR"
export const UPDATE_PROFILE_PICTURE_BEGIN = "UPDATE_PROFILE_PICTURE_BEGIN"


//comment
export const CREATE_COMMENT_BEGIN = "CREATE_COMMENT_BEGIN"
export const CREATE_COMMENT_SUCCESS = ""
export const CREATE_COMMENT_ERROR = ""
export const UPDATE_COMMENT_BEGIN = ""
export const UPDATE_COMMENT_SUCCESS= ""
export const UPDATE_COMMENT_ERROR = ""
export const REMOVE_COMMENT_BEGIN = ""
export const REMOVE_COMMENT_SUCCESS = ""
export const REMOVE_COMMENT_ERROR = ""


//payment
